name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Set up de Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalacion de dependencias
      run: npm install

    - name: Iniciar ESLint
      run: npx eslint src/**/*.js
